# Generated by Django 4.2.16 on 2025-02-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_siteimage_service_description_service_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='siteimage',
            name='name',
        ),
        migrations.AddField(
            model_name='siteimage',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default=3, upload_to='service_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(choices=[('Graphics Design', 'Graphics Design'), ('Construction', 'Construction'), ('Cyber Services', 'Cyber Services'), ('Entertainment', 'Entertainment')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='description',
            field=models.CharField(default=6, max_length=255),
            preserve_default=False,
        ),
    ]
