# Generated by Django 4.2.16 on 2025-02-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default='samamwa13@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(default='+254715825808', max_length=15),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(default='+254715825808', max_length=15),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
